version: "3.8"

services:

  postgres-staging:
    image: postgres:16
    container_name: postgres-staging

    environment:
      POSTGRES_DB: flex_staging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_staging_data:/var/lib/postgresql/data

    restart: unless-stopped

  postgres-dwh:
    image: postgres:16
    container_name: postgres-dwh

    environment:
      POSTGRES_DB: flex_dwh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5434:5432"

    volumes:
      - postgres_dwh_data:/var/lib/postgresql/data

    restart: unless-stopped

  spark-master:
    image: apache/spark:3.5.1

    container_name: spark-master

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    volumes:
      - ./spark_jobs:/opt/spark_jobs
      - ./jars:/opt/jars
    ports:
      - "7077:7077"
      - "8080:8080"

    restart: unless-stopped

  spark-worker:
    image: apache/spark:3.5.1

    container_name: spark-worker

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - ./spark_jobs:/opt/spark_jobs
      - ./jars:/opt/jars

    depends_on:
      - spark-master

    restart: unless-stopped

  postgres-airflow:
    image: postgres:16

    container_name: postgres-airflow

    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow

    restart: unless-stopped

  airflow-init:
    build:
      context: ./airflow
      dockerfile: Dockerfile

    depends_on:
      - postgres-airflow

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow

    entrypoint: /bin/bash

    command:
      - -c
      - |
        sleep 20

        airflow db migrate

        airflow users create \
        --username admin \
        --password admin \
        --firstname Flex \
        --lastname Eau \
        --role Admin \
        --email admin@flexeau.sn

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./:/opt/project
  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile

    container_name: airflow-scheduler

    depends_on:
      - postgres-airflow
      - spark-master
      - postgres-staging
      - postgres-dwh

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow

    command: scheduler

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./:/opt/project
      - ./jars:/opt/jars

    restart: unless-stopped

  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile

    container_name: airflow-webserver

    depends_on:
      - postgres-airflow

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow

    command: webserver

    ports:
      - "8081:8080"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./:/opt/project
      - ./jars:/opt/jars

    restart: unless-stopped


volumes:
  postgres_staging_data:
  postgres_dwh_data:
  postgres_airflow_data: